[package]
name = "fish_speech_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "fish_speech_core"
path = "lib/lib.rs"

[features]
cuda = ["candle-core/cuda", "candle-nn/cuda", "candle-transformers/cuda"]
metal = ["candle-core/metal", "candle-nn/metal", "candle-transformers/metal"]

[dependencies]
anyhow = "1.0.86"
byteorder = "1.5.0"
# TODO: Fix when 0.7.1 is released to Cargo
candle-core = { git = "https://github.com/huggingface/candle", rev = "d01207dbf3fb0ad614e7915c8f5706fbc09902fb" }
candle-nn = { git = "https://github.com/huggingface/candle", rev = "d01207dbf3fb0ad614e7915c8f5706fbc09902fb" }
candle-transformers = { git = "https://github.com/huggingface/candle", rev = "d01207dbf3fb0ad614e7915c8f5706fbc09902fb" }
clap = { version = "4.5.16", features = ["derive"] }
hf-hub = "0.3.2"
rand = "0.8.5"
regex = "1.10.6"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.127"
symphonia = "0.5.4"
thiserror = "1.0.63"
tokenizers = "0.20.0"
