[project]
name = "fish_speech_python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["maturin>=1.7.1"]


[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
